# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    python-build:
        name: Build and Install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main

            - name: Initialize Python 3.9
              uses: actions/setup-python@v1
              with:
                python-version: 3.9

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8
         
            - name: Lint with flake8
              run: |
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
            - name: Build binary wheel and a source tarball
              run: |
                python setup.py bdist_wheel sdist
                pip install .
              
